/**
 * Transactional event-application core shared by the real WorkflowRunDO and
 * the in-memory test mocks.
 *
 * All guard checks, the event append, and the entity mutation happen against a
 * single {@link EventStore}. The Durable Object wraps a call to
 * {@link applyEvent} in `ctx.storage.transaction()`, so the whole operation is
 * atomic; the mocks run it against an in-memory store.
 *
 * Guard semantics are ported from the upstream `@workflow/world-local` /
 * `@workflow/world-postgres` reference implementations (4.2.x contract):
 * - run_started on a terminal run -> RunExpiredError
 * - terminal transitions on a terminal run -> EntityConflictError
 * - run_cancelled is idempotent on an already-cancelled run
 * - duplicate step_created / hook_created -> EntityConflictError
 * - step events on a terminal step -> EntityConflictError
 * - step_started before step.retryAfter -> TooEarlyError
 * - error/output/completedAt are cleared whenever a run re-enters a
 *   non-final status (WorkflowRunSchema is a discriminated union)
 *
 * Errors are returned as structured outcomes (never thrown) because custom
 * error classes do not survive the Durable Object RPC boundary with their
 * `name` intact — and `@workflow/errors` matches errors by name via `.is()`.
 * The storage layer converts outcomes back into the typed errors.
 */

import type {
  CreateEventRequest,
  Event,
  Hook,
  RunCreatedEventRequest,
  Step,
  WorkflowRun,
} from '@workflow/world';
import {
  EventSchema,
  HookSchema,
  isLegacySpecVersion,
  isTerminalStepStatus,
  isTerminalWorkflowRunStatus,
  requiresNewerWorld,
  SPEC_VERSION_CURRENT,
  StepSchema,
  WorkflowRunSchema,
} from '@workflow/world';
import { compact } from './util.js';

/** Storage key for the run entity. */
const RUN_KEY = 'run';
/** Key prefixes for per-entity storage. ULID-suffixed keys list in order. */
export const EVENT_KEY_PREFIX = 'event:';
export const STEP_KEY_PREFIX = 'step:';
export const HOOK_KEY_PREFIX = 'hook:';
/**
 * Marker recording that a hook_created event was committed for a hookId.
 * Mirrors postgres' `workflow_events_entity_creation_unique` partial index:
 * it outlives hook disposal so a replayed hook_created after dispose is
 * rejected as a duplicate instead of resurrecting the hook.
 */
const HOOK_EVENT_MARKER_PREFIX = 'hookevent:';

export interface EventStoreListOptions {
  prefix: string;
  /** Exclusive lower bound (full key). */
  startAfter?: string;
  /** Exclusive upper bound (full key). */
  end?: string;
  limit?: number;
  reverse?: boolean;
}

/**
 * Minimal transactional key-value surface, satisfied by
 * `DurableObjectTransaction` / `DurableObjectStorage` and by the in-memory
 * test-mock store. Keys list in lexicographic order (reversed when
 * `reverse: true`).
 */
export interface EventStore {
  get<T>(key: string): Promise<T | undefined>;
  put<T>(key: string, value: T): Promise<void>;
  delete(key: string): Promise<boolean>;
  list<T>(options: EventStoreListOptions): Promise<Map<string, T>>;
}

export interface ApplyEventRequest {
  /** The effective run id (already resolved / generated by the caller). */
  runId: string;
  data: CreateEventRequest | RunCreatedEventRequest;
  /**
   * Current holder of the hook token per the global KV token index
   * (hook_created only). `null` means the token is unclaimed.
   */
  tokenHolder?: { runId: string; hookId: string } | null;
}

export type ApplyEventErrorCode =
  | 'RUN_NOT_FOUND'
  | 'STEP_NOT_FOUND'
  | 'HOOK_NOT_FOUND'
  | 'ENTITY_CONFLICT'
  | 'RUN_EXPIRED'
  | 'TOO_EARLY'
  | 'RUN_NOT_SUPPORTED'
  | 'LEGACY_RUN_NOT_SUPPORTED';

export interface ApplyEventFailure {
  ok: false;
  code: ApplyEventErrorCode;
  message: string;
  /** Seconds until retry is allowed (TOO_EARLY only). */
  retryAfterSeconds?: number;
  /** The run's spec version (RUN_NOT_SUPPORTED only). */
  runSpecVersion?: number;
}

export interface ApplyEventSuccess {
  ok: true;
  /** Absent for idempotent replays that record no new event. */
  event?: Event;
  run?: WorkflowRun;
  step?: Step;
  hook?: Hook;
  /** Hooks whose tokens must be released from the global KV index. */
  releasedHooks: Array<{ hookId: string; token: string }>;
  /** Set when a run entity was created (run_created or resilient bootstrap). */
  runCreated?: { workflowName: string; createdAt: Date };
  /** Set when the global KV hook index must be (re)written. */
  hookToIndex?: Hook;
  /** All events (ascending), preloaded for run_started responses. */
  events?: Event[];
}

export type ApplyEventOutcome = ApplyEventSuccess | ApplyEventFailure;

interface ApplyEventContext extends ApplyEventRequest {
  nextEventId(): string;
  now: Date;
}

function failure(
  code: ApplyEventErrorCode,
  message: string,
  extra?: Pick<ApplyEventFailure, 'retryAfterSeconds' | 'runSpecVersion'>,
): ApplyEventFailure {
  return { ok: false, code, message, ...extra };
}

function readStringProp(value: unknown, key: string): string | undefined {
  if (value !== null && typeof value === 'object') {
    const prop = (value as Record<string, unknown>)[key];
    if (typeof prop === 'string') return prop;
  }
  return undefined;
}

/**
 * Map a failure eventData.error (which may be a string, an Error-shaped
 * object, or anything else) to the structured error stored on entities.
 * Matches upstream: string errors keep their text, errorCode is preserved.
 */
function toStructuredError(
  error: unknown,
  opts?: { stack?: string; code?: string },
): { message: string; stack?: string; code?: string } {
  const message =
    typeof error === 'string' ? error : (readStringProp(error, 'message') ?? 'Unknown error');
  return {
    message,
    stack: opts?.stack ?? readStringProp(error, 'stack'),
    code: opts?.code ?? readStringProp(error, 'code'),
  };
}

/**
 * Shared cursor pagination over a key prefix. Fetches `limit + 1` entries to
 * detect `hasMore` without ever skipping the boundary entry (the cursor is
 * derived from the last *returned* item, not the peeked one).
 */
export async function listByPrefix<T>(
  store: EventStore,
  prefix: string,
  params: { limit: number; cursor?: string; sortOrder?: 'asc' | 'desc' },
  getId: (item: T) => string,
): Promise<{ data: T[]; cursor: string | null; hasMore: boolean }> {
  const { limit, cursor, sortOrder = 'asc' } = params;
  const options: EventStoreListOptions =
    sortOrder === 'desc'
      ? { prefix, reverse: true, limit: limit + 1, end: cursor ? `${prefix}${cursor}` : undefined }
      : { prefix, limit: limit + 1, startAfter: cursor ? `${prefix}${cursor}` : undefined };
  const entries = await store.list<T>(options);
  const values = Array.from(entries.values());
  const hasMore = values.length > limit;
  const data = values.slice(0, limit);
  const last = data.at(-1);
  return {
    data,
    cursor: hasMore && last !== undefined ? getId(last) : null,
    hasMore,
  };
}

/** Delete all hook entities for the run, returning the released tokens. */
async function releaseAllHooks(
  store: EventStore,
): Promise<Array<{ hookId: string; token: string }>> {
  const hooks = await store.list<Hook>({ prefix: HOOK_KEY_PREFIX });
  const released: Array<{ hookId: string; token: string }> = [];
  for (const hook of hooks.values()) {
    await store.delete(`${HOOK_KEY_PREFIX}${hook.hookId}`);
    released.push({ hookId: hook.hookId, token: hook.token });
  }
  return released;
}

export async function applyEvent(
  store: EventStore,
  ctx: ApplyEventContext,
): Promise<ApplyEventOutcome> {
  const { runId, data, now } = ctx;
  const specVersion = data.specVersion ?? SPEC_VERSION_CURRENT;

  /** Build and validate the stored event BEFORE anything is persisted. */
  const buildEvent = (record: Record<string, unknown>): Event => {
    const withMeta: Record<string, unknown> = {
      ...record,
      runId,
      eventId: ctx.nextEventId(),
      createdAt: now,
      specVersion,
    };
    // eventData belongs on run_created only; run_started must not carry it.
    if (record.eventType === 'run_started') {
      delete withMeta.eventData;
    }
    return EventSchema.parse(compact(withMeta));
  };

  const putEvent = async (event: Event): Promise<void> => {
    await store.put(`${EVENT_KEY_PREFIX}${event.eventId}`, event);
  };

  // ============================================================
  // VALIDATION: current run state (skipped for run_created and for
  // step_completed / step_retrying, matching upstream — those only operate
  // on running steps regardless of run state).
  // ============================================================
  let currentRun: WorkflowRun | undefined;
  const skipRunValidation =
    data.eventType === 'run_created' ||
    data.eventType === 'step_completed' ||
    data.eventType === 'step_retrying';
  if (!skipRunValidation) {
    currentRun = await store.get<WorkflowRun>(RUN_KEY);
  }

  // ============================================================
  // RESILIENT START: run_started on a non-existent run bootstraps the run
  // from the message's runInput (spec >= 3 queue transport).
  // ============================================================
  let bootstrapped: ApplyEventSuccess['runCreated'];
  if (data.eventType === 'run_started' && !currentRun && data.eventData) {
    const { deploymentId, workflowName, input, executionContext } = data.eventData;
    if (deploymentId && workflowName && input !== undefined) {
      const createdRun = WorkflowRunSchema.parse(
        compact({
          runId,
          deploymentId,
          workflowName,
          specVersion,
          executionContext,
          input,
          status: 'pending',
          output: undefined,
          error: undefined,
          startedAt: undefined,
          completedAt: undefined,
          createdAt: now,
          updatedAt: now,
        }),
      );
      const runCreatedEvent = buildEvent({
        eventType: 'run_created',
        eventData: { deploymentId, workflowName, input, executionContext },
      });
      await store.put(RUN_KEY, createdRun);
      await putEvent(runCreatedEvent);
      currentRun = createdRun;
      bootstrapped = { workflowName, createdAt: now };
    }
  }

  // ============================================================
  // VERSION COMPATIBILITY
  // ============================================================
  if (currentRun) {
    if (requiresNewerWorld(currentRun.specVersion)) {
      return failure(
        'RUN_NOT_SUPPORTED',
        `Run "${runId}" requires a newer world (run specVersion ${currentRun.specVersion}, world ${SPEC_VERSION_CURRENT})`,
        { runSpecVersion: currentRun.specVersion },
      );
    }
    if (isLegacySpecVersion(currentRun.specVersion)) {
      return failure(
        'LEGACY_RUN_NOT_SUPPORTED',
        `Run "${runId}" was created with a legacy spec version (${currentRun.specVersion ?? 'undefined'}) not supported by this world`,
      );
    }
  }

  // ============================================================
  // GUARDS: terminal run state
  // ============================================================
  if (currentRun && isTerminalWorkflowRunStatus(currentRun.status)) {
    // Idempotent: run_cancelled on an already-cancelled run records the event
    // and returns the current state.
    if (data.eventType === 'run_cancelled' && currentRun.status === 'cancelled') {
      const event = buildEvent({ ...data });
      await putEvent(event);
      return { ok: true, event, run: currentRun, releasedHooks: [] };
    }
    if (data.eventType === 'run_started') {
      return failure(
        'RUN_EXPIRED',
        `Workflow run "${runId}" is already in terminal state "${currentRun.status}"`,
      );
    }
    if (
      data.eventType === 'run_completed' ||
      data.eventType === 'run_failed' ||
      data.eventType === 'run_cancelled'
    ) {
      return failure(
        'ENTITY_CONFLICT',
        `Cannot transition run from terminal state "${currentRun.status}"`,
      );
    }
    if (
      data.eventType === 'step_created' ||
      data.eventType === 'hook_created' ||
      data.eventType === 'wait_created'
    ) {
      return failure(
        'ENTITY_CONFLICT',
        `Cannot create new entities on run in terminal state "${currentRun.status}"`,
      );
    }
  }

  // ============================================================
  // GUARDS: step ordering and terminal state
  // ============================================================
  let validatedStep: Step | undefined;
  if (
    data.eventType === 'step_started' ||
    data.eventType === 'step_completed' ||
    data.eventType === 'step_failed' ||
    data.eventType === 'step_retrying'
  ) {
    validatedStep = await store.get<Step>(`${STEP_KEY_PREFIX}${data.correlationId}`);
    if (!validatedStep) {
      return failure('STEP_NOT_FOUND', `Step "${data.correlationId}" not found`);
    }
    if (isTerminalStepStatus(validatedStep.status)) {
      return failure(
        'ENTITY_CONFLICT',
        `Cannot modify step in terminal state "${validatedStep.status}"`,
      );
    }
    // On terminal runs, only in-flight steps may still record progress.
    if (
      currentRun &&
      isTerminalWorkflowRunStatus(currentRun.status) &&
      validatedStep.status !== 'running'
    ) {
      return failure(
        'RUN_EXPIRED',
        `Cannot modify non-running step on run in terminal state "${currentRun.status}"`,
      );
    }
  }

  // ============================================================
  // GUARDS: hook event ordering
  // ============================================================
  if (
    (data.eventType === 'hook_disposed' || data.eventType === 'hook_received') &&
    data.correlationId
  ) {
    const existingHook = await store.get<Hook>(`${HOOK_KEY_PREFIX}${data.correlationId}`);
    if (!existingHook) {
      return failure('HOOK_NOT_FOUND', `Hook "${data.correlationId}" not found`);
    }
  }

  // Non-run_created events require the run to exist (after the resilient
  // start bootstrap had its chance). step_completed / step_retrying skip the
  // run read entirely — their step guard above already proves the run exists.
  if (!skipRunValidation && data.eventType !== 'run_started' && !currentRun) {
    return failure('RUN_NOT_FOUND', `Workflow run "${runId}" not found`);
  }

  // ============================================================
  // EVENT + ENTITY WRITES (single transaction)
  // ============================================================
  switch (data.eventType) {
    case 'run_created': {
      const existing = await store.get<WorkflowRun>(RUN_KEY);
      if (existing) {
        // Idempotent replay: return the existing run without appending a
        // duplicate run_created event to the log.
        return { ok: true, run: existing, releasedHooks: [] };
      }
      const run = WorkflowRunSchema.parse(
        compact({
          runId,
          deploymentId: data.eventData.deploymentId,
          workflowName: data.eventData.workflowName,
          specVersion,
          executionContext: data.eventData.executionContext,
          input: data.eventData.input,
          status: 'pending',
          output: undefined,
          error: undefined,
          startedAt: undefined,
          completedAt: undefined,
          createdAt: now,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(RUN_KEY, run);
      await putEvent(event);
      return {
        ok: true,
        event,
        run,
        releasedHooks: [],
        runCreated: { workflowName: data.eventData.workflowName, createdAt: now },
      };
    }

    case 'run_started': {
      if (!currentRun) {
        return failure('RUN_NOT_FOUND', `Workflow run "${runId}" not found`);
      }
      // Idempotent for concurrent invocations / queue redeliveries: if the
      // run is already running this is a replay — no duplicate event.
      if (currentRun.status === 'running') {
        return { ok: true, run: currentRun, releasedHooks: [] };
      }
      const run = WorkflowRunSchema.parse(
        compact({
          ...currentRun,
          status: 'running',
          output: undefined,
          error: undefined,
          completedAt: undefined,
          startedAt: currentRun.startedAt ?? now,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(RUN_KEY, run);
      await putEvent(event);
      // Preload all events so the runtime can skip the initial events.list.
      const allEvents = await listByPrefix<Event>(
        store,
        EVENT_KEY_PREFIX,
        { limit: 1000, sortOrder: 'asc' },
        (e) => e.eventId,
      );
      return {
        ok: true,
        event,
        run,
        releasedHooks: [],
        runCreated: bootstrapped,
        events: allEvents.data,
      };
    }

    case 'run_completed': {
      if (!currentRun) {
        return failure('RUN_NOT_FOUND', `Workflow run "${runId}" not found`);
      }
      const run = WorkflowRunSchema.parse(
        compact({
          ...currentRun,
          status: 'completed',
          output: data.eventData.output,
          error: undefined,
          completedAt: now,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(RUN_KEY, run);
      await putEvent(event);
      const releasedHooks = await releaseAllHooks(store);
      return { ok: true, event, run, releasedHooks };
    }

    case 'run_failed': {
      if (!currentRun) {
        return failure('RUN_NOT_FOUND', `Workflow run "${runId}" not found`);
      }
      const run = WorkflowRunSchema.parse(
        compact({
          ...currentRun,
          status: 'failed',
          output: undefined,
          error: toStructuredError(data.eventData.error, {
            code: data.eventData.errorCode ?? readStringProp(data.eventData.error, 'code'),
          }),
          completedAt: now,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(RUN_KEY, run);
      await putEvent(event);
      const releasedHooks = await releaseAllHooks(store);
      return { ok: true, event, run, releasedHooks };
    }

    case 'run_cancelled': {
      if (!currentRun) {
        return failure('RUN_NOT_FOUND', `Workflow run "${runId}" not found`);
      }
      const run = WorkflowRunSchema.parse(
        compact({
          ...currentRun,
          status: 'cancelled',
          output: undefined,
          error: undefined,
          completedAt: now,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(RUN_KEY, run);
      await putEvent(event);
      const releasedHooks = await releaseAllHooks(store);
      return { ok: true, event, run, releasedHooks };
    }

    case 'step_created': {
      const stepKey = `${STEP_KEY_PREFIX}${data.correlationId}`;
      const existing = await store.get<Step>(stepKey);
      if (existing) {
        // Core catches EntityConflictError for exactly this replay case
        // ("Step already exists, continuing").
        return failure('ENTITY_CONFLICT', `Step "${data.correlationId}" already exists`);
      }
      const step = StepSchema.parse(
        compact({
          runId,
          stepId: data.correlationId,
          stepName: data.eventData.stepName,
          status: 'pending',
          input: data.eventData.input,
          output: undefined,
          error: undefined,
          attempt: 0,
          startedAt: undefined,
          completedAt: undefined,
          retryAfter: undefined,
          createdAt: now,
          updatedAt: now,
          specVersion,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(stepKey, step);
      await putEvent(event);
      return { ok: true, event, step, releasedHooks: [] };
    }

    case 'step_started': {
      const step = validatedStep;
      if (!step) {
        return failure('STEP_NOT_FOUND', `Step "${data.correlationId}" not found`);
      }
      if (step.retryAfter && step.retryAfter.getTime() > now.getTime()) {
        return failure(
          'TOO_EARLY',
          `Cannot start step "${data.correlationId}": retryAfter timestamp has not been reached yet`,
          {
            retryAfterSeconds: Math.ceil((step.retryAfter.getTime() - now.getTime()) / 1000),
          },
        );
      }
      const updated = StepSchema.parse(
        compact({
          ...step,
          status: 'running',
          // Only set startedAt on the first start; increment attempt each start.
          startedAt: step.startedAt ?? now,
          attempt: step.attempt + 1,
          retryAfter: undefined,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(`${STEP_KEY_PREFIX}${data.correlationId}`, updated);
      await putEvent(event);
      return { ok: true, event, step: updated, releasedHooks: [] };
    }

    case 'step_completed': {
      const step = validatedStep;
      if (!step) {
        return failure('STEP_NOT_FOUND', `Step "${data.correlationId}" not found`);
      }
      const updated = StepSchema.parse(
        compact({
          ...step,
          status: 'completed',
          output: data.eventData.result,
          completedAt: now,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(`${STEP_KEY_PREFIX}${data.correlationId}`, updated);
      await putEvent(event);
      return { ok: true, event, step: updated, releasedHooks: [] };
    }

    case 'step_failed': {
      const step = validatedStep;
      if (!step) {
        return failure('STEP_NOT_FOUND', `Step "${data.correlationId}" not found`);
      }
      const updated = StepSchema.parse(
        compact({
          ...step,
          status: 'failed',
          error: toStructuredError(data.eventData.error, { stack: data.eventData.stack }),
          completedAt: now,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(`${STEP_KEY_PREFIX}${data.correlationId}`, updated);
      await putEvent(event);
      return { ok: true, event, step: updated, releasedHooks: [] };
    }

    case 'step_retrying': {
      const step = validatedStep;
      if (!step) {
        return failure('STEP_NOT_FOUND', `Step "${data.correlationId}" not found`);
      }
      const updated = StepSchema.parse(
        compact({
          ...step,
          status: 'pending',
          error: toStructuredError(data.eventData.error, { stack: data.eventData.stack }),
          retryAfter: data.eventData.retryAfter ? new Date(data.eventData.retryAfter) : undefined,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(`${STEP_KEY_PREFIX}${data.correlationId}`, updated);
      await putEvent(event);
      return { ok: true, event, step: updated, releasedHooks: [] };
    }

    case 'hook_created': {
      const hookId = data.correlationId;
      const token = data.eventData.token;
      const holder = ctx.tokenHolder ?? null;
      const markerKey = `${HOOK_EVENT_MARKER_PREFIX}${hookId}`;
      const hookKey = `${HOOK_KEY_PREFIX}${hookId}`;

      if (holder && (holder.runId !== runId || holder.hookId !== hookId)) {
        // A different (runId, hookId) holds this token. Record a
        // hook_conflict event carrying conflictingRunId so the claiming
        // workflow fails deterministically when the hook is awaited. The
        // legitimate holder's KV index entry is left untouched.
        const event = buildEvent({
          eventType: 'hook_conflict',
          correlationId: hookId,
          eventData: { token, conflictingRunId: holder.runId },
        });
        await putEvent(event);
        return { ok: true, event, releasedHooks: [] };
      }

      const existingMarker = await store.get<string>(markerKey);
      if (existingMarker !== undefined) {
        const existingHook = await store.get<Hook>(hookKey);
        if (existingHook && !holder) {
          // Crash orphan: hook + event committed but the global KV index
          // write was lost. Complete the partial write by re-indexing.
          return { ok: true, hook: existingHook, hookToIndex: existingHook, releasedHooks: [] };
        }
        // Fully-committed duplicate (or re-create after disposal): reject so
        // the runtime's concurrent-replay catch path can swallow it.
        return failure('ENTITY_CONFLICT', `Hook "${hookId}" already created`);
      }

      const hook = HookSchema.parse(
        compact({
          runId,
          hookId,
          token,
          metadata: data.eventData.metadata,
          ownerId: '',
          projectId: '',
          environment: '',
          createdAt: now,
          specVersion,
          isWebhook: data.eventData.isWebhook ?? false,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(hookKey, hook);
      await store.put(markerKey, event.eventId);
      await putEvent(event);
      return { ok: true, event, hook, hookToIndex: hook, releasedHooks: [] };
    }

    case 'hook_disposed': {
      const hookKey = `${HOOK_KEY_PREFIX}${data.correlationId}`;
      // Existence was validated above; read again for the token.
      const hook = await store.get<Hook>(hookKey);
      if (!hook) {
        return failure('HOOK_NOT_FOUND', `Hook "${data.correlationId}" not found`);
      }
      await store.delete(hookKey);
      const event = buildEvent({ ...data });
      await putEvent(event);
      return {
        ok: true,
        event,
        releasedHooks: [{ hookId: hook.hookId, token: hook.token }],
      };
    }

    // hook_received, hook_conflict, wait_created, wait_completed are
    // event-only at the storage level for this world.
    default: {
      const event = buildEvent({ ...data });
      await putEvent(event);
      return { ok: true, event, releasedHooks: [] };
    }
  }
}
