/**
 * Transactional event-application core shared by the real WorkflowRunDO and
 * the in-memory test mocks.
 *
 * All guard checks, the slot allocation, the event append, and the entity
 * mutation happen against a single {@link EventStore}. The Durable Object
 * wraps a call to {@link applyEvent} in `ctx.storage.transaction()`, so the
 * whole operation is atomic; the mocks run it against an in-memory store.
 *
 * Event ids are v5 slots: `evnt_` + the event's dense 1-based position in the
 * run's log, formatted by `slotToEventId`. The base slot is read from the
 * store inside the same transaction that commits the append, so allocation is
 * store-settled: no writer can take a slot without the transaction that
 * appends its event.
 *
 * Guard semantics are ported from the upstream `@workflow/world-local` /
 * `@workflow/world-postgres` reference implementations (5.x contract):
 * - run_started on a terminal run -> RunExpiredError
 * - terminal transitions on a terminal run -> EntityConflictError
 * - run_cancelled is idempotent on an already-cancelled run
 * - duplicate step/hook/wait creation -> EntityConflictError
 * - step events on a terminal step -> EntityConflictError
 * - step_started before step.retryAfter -> TooEarlyError
 * - attr_set on a terminal run -> EntityConflictError
 * - a stale `eventCount` never rejects a write: the event commits at the next
 *   free slot and the skipped span is reported (bump-and-report)
 *
 * Errors are returned as structured outcomes (never thrown) because custom
 * error classes do not survive the Durable Object RPC boundary with their
 * `name` intact, and `@workflow/errors` matches errors by name via `.is()`.
 * The storage layer converts outcomes back into the typed errors.
 */

import type {
  AttributeChange,
  CreateEventRequest,
  Event,
  Hook,
  RunCreatedEventRequest,
  Step,
  Wait,
  WorkflowRun,
} from '@workflow/world';
import {
  applyAttributeChanges,
  EventSchema,
  eventIdToSlot,
  FIRST_EVENT_SLOT,
  HookSchema,
  isChildEntityCreationEvent,
  isLegacySpecVersion,
  isTerminalStepStatus,
  isTerminalWorkflowRunStatus,
  requiresNewerWorld,
  SPEC_VERSION_CURRENT,
  slotToEventId,
  StepSchema,
  validateAttributeChanges,
  WaitSchema,
  WorkflowRunSchema,
} from '@workflow/world';
import { compact } from './util.js';

/** Storage key for the run entity. */
const RUN_KEY = 'run';
/** Key prefixes for per-entity storage. Slot-numbered event ids are
 * zero-padded, so lexicographic key order equals positional order. */
export const EVENT_KEY_PREFIX = 'event:';
export const STEP_KEY_PREFIX = 'step:';
export const WAIT_KEY_PREFIX = 'wait:';
export const HOOK_KEY_PREFIX = 'hook:';
/**
 * Marker recording that a hook_created event was committed for a hookId.
 * Mirrors postgres' `workflow_events_entity_creation_unique` partial index:
 * it outlives hook disposal so a replayed hook_created after dispose is
 * rejected as a duplicate instead of resurrecting the hook.
 */
const HOOK_EVENT_MARKER_PREFIX = 'hookevent:';
/** Dedup claim for workflow-writer attr_set events, keyed by correlationId,
 * so a replayed attr_set cannot apply (or log) twice. */
const ATTR_EVENT_MARKER_PREFIX = 'attrevent:';

export interface EventStoreListOptions {
  prefix: string;
  /** Exclusive lower bound (full key). */
  startAfter?: string;
  /** Exclusive upper bound (full key). */
  end?: string;
  limit?: number;
  reverse?: boolean;
}

/**
 * Minimal transactional key-value surface, satisfied by
 * `DurableObjectTransaction` / `DurableObjectStorage` and by the in-memory
 * test-mock store. Keys list in lexicographic order (reversed when
 * `reverse: true`).
 */
export interface EventStore {
  get<T>(key: string): Promise<T | undefined>;
  put<T>(key: string, value: T): Promise<void>;
  delete(key: string): Promise<boolean>;
  list<T>(options: EventStoreListOptions): Promise<Map<string, T>>;
}

export interface ApplyEventRequest {
  /** The effective run id (already resolved / generated by the caller). */
  runId: string;
  data: CreateEventRequest | RunCreatedEventRequest;
  /**
   * Current holder of the hook token per the global KV token index
   * (hook_created only). `null` means the token is unclaimed.
   */
  tokenHolder?: { runId: string; hookId: string } | null;
  /** `CreateEventParams.eventCount`: how many events the writer held when it
   * decided to write. A committed slot above `eventCount + 1` triggers the
   * report half of bump-and-report. */
  eventCount?: number;
  /** `CreateEventParams.skipPreload`: omit the run_started event preload. */
  skipPreload?: boolean;
  /** `CreateEventParams.sinceCursor`: return the delta of events strictly
   * after this cursor with the success response (events.list semantics). */
  sinceCursor?: string;
}

export type ApplyEventErrorCode =
  | 'RUN_NOT_FOUND'
  | 'STEP_NOT_FOUND'
  | 'WAIT_NOT_FOUND'
  | 'HOOK_NOT_FOUND'
  | 'ENTITY_CONFLICT'
  | 'RUN_EXPIRED'
  | 'TOO_EARLY'
  | 'ATTRIBUTE_INVALID'
  | 'RUN_NOT_SUPPORTED'
  | 'LEGACY_RUN_NOT_SUPPORTED';

export interface ApplyEventFailure {
  ok: false;
  code: ApplyEventErrorCode;
  message: string;
  /** Seconds until retry is allowed (TOO_EARLY only). */
  retryAfterSeconds?: number;
  /** The run's spec version (RUN_NOT_SUPPORTED only). */
  runSpecVersion?: number;
}

export interface EventPage {
  events: Event[];
  cursor: string | null;
  hasMore: boolean;
}

export interface ApplyEventSuccess {
  ok: true;
  /** Absent for idempotent replays that record no new event. */
  event?: Event;
  run?: WorkflowRun;
  step?: Step;
  hook?: Hook;
  wait?: Wait;
  /** Set when a lazy step_started atomically created its step: the runtime's
   * exactly-once inline-execution ownership signal. */
  stepCreated?: true;
  /** Hooks whose tokens must be released from the global KV index. */
  releasedHooks: Array<{ hookId: string; token: string }>;
  /** Set when a run entity was created (run_created or resilient bootstrap). */
  runCreated?: { workflowName: string; createdAt: Date };
  /** Set when the global KV hook index must be (re)written. */
  hookToIndex?: Hook;
  /** run_started preload, sinceCursor delta, or the skipped-slot report. */
  eventPage?: EventPage;
}

export type ApplyEventOutcome = ApplyEventSuccess | ApplyEventFailure;

interface ApplyEventContext extends ApplyEventRequest {
  now: Date;
}

function failure(
  code: ApplyEventErrorCode,
  message: string,
  extra?: Pick<ApplyEventFailure, 'retryAfterSeconds' | 'runSpecVersion'>,
): ApplyEventFailure {
  return { ok: false, code, message, ...extra };
}

/**
 * Shared cursor pagination over a key prefix. Fetches `limit + 1` entries to
 * detect `hasMore` without ever skipping the boundary entry (the cursor is
 * derived from the last *returned* item, not the peeked one).
 */
export async function listByPrefix<T>(
  store: EventStore,
  prefix: string,
  params: { limit: number; cursor?: string; sortOrder?: 'asc' | 'desc' },
  getId: (item: T) => string,
): Promise<{ data: T[]; cursor: string | null; hasMore: boolean }> {
  const { limit, cursor, sortOrder = 'asc' } = params;
  const options: EventStoreListOptions =
    sortOrder === 'desc'
      ? { prefix, reverse: true, limit: limit + 1, end: cursor ? `${prefix}${cursor}` : undefined }
      : { prefix, limit: limit + 1, startAfter: cursor ? `${prefix}${cursor}` : undefined };
  const entries = await store.list<T>(options);
  const values = Array.from(entries.values());
  const hasMore = values.length > limit;
  const data = values.slice(0, limit);
  const last = data.at(-1);
  return {
    data,
    cursor: hasMore && last !== undefined ? getId(last) : null,
    hasMore,
  };
}

/** Read the highest committed slot inside the caller's transaction. Returns
 * null when the log's last id is not slot-numbered (a ULID-era run). */
async function lastCommittedSlot(store: EventStore): Promise<number | null> {
  const entries = await store.list<Event>({ prefix: EVENT_KEY_PREFIX, limit: 1, reverse: true });
  const last = entries.values().next().value;
  if (last === undefined) return 0;
  return eventIdToSlot(last.eventId);
}

/** Full-log preload for run_started responses (events.list semantics with the
 * whole log on one page). */
async function preloadAllEvents(store: EventStore): Promise<EventPage> {
  const entries = await store.list<Event>({ prefix: EVENT_KEY_PREFIX });
  const events = Array.from(entries.values());
  return { events, cursor: events.at(-1)?.eventId ?? null, hasMore: false };
}

/** Delete all hook entities for the run, returning the released tokens. */
async function releaseAllHooks(
  store: EventStore,
): Promise<Array<{ hookId: string; token: string }>> {
  const hooks = await store.list<Hook>({ prefix: HOOK_KEY_PREFIX });
  const released: Array<{ hookId: string; token: string }> = [];
  for (const hook of hooks.values()) {
    await store.delete(`${HOOK_KEY_PREFIX}${hook.hookId}`);
    released.push({ hookId: hook.hookId, token: hook.token });
  }
  return released;
}

/** Delete all wait entities for the run (terminal-run cleanup). */
async function deleteAllWaits(store: EventStore): Promise<void> {
  const waits = await store.list<Wait>({ prefix: WAIT_KEY_PREFIX });
  for (const key of waits.keys()) {
    await store.delete(key);
  }
}

/** Validate a batch of attribute changes, converting the thrown
 * AttributeValidationError into a structured outcome for the RPC boundary. */
function validateAttributes(
  changes: AttributeChange[],
  context: { existingKeys?: Iterable<string>; allowReservedAttributes?: boolean },
): ApplyEventFailure | null {
  try {
    validateAttributeChanges(changes, context);
    return null;
  } catch (error) {
    return failure('ATTRIBUTE_INVALID', error instanceof Error ? error.message : String(error));
  }
}

/** Attribute changes equivalent to seeding `attributes` at run creation. */
function seedAttributeChanges(attributes: Record<string, string> | undefined): AttributeChange[] {
  return Object.entries(attributes ?? {}).map(([key, value]) => ({ key, value }));
}

export async function applyEvent(
  store: EventStore,
  ctx: ApplyEventContext,
): Promise<ApplyEventOutcome> {
  const outcome = await applyEventCore(store, ctx);
  if (!outcome.ok) return outcome;
  return decorateWithEventPage(store, ctx, outcome);
}

/**
 * Attach the response event page, still inside the caller's transaction so
 * every variant is computed against the exact log the write committed into.
 * Priority mirrors world-local/world-redis: the sinceCursor delta wins (it is
 * a strict superset of the skipped span and the only one that advances the
 * caller's cursor), then a preload set by the core, then bump-and-report.
 */
async function decorateWithEventPage(
  store: EventStore,
  ctx: ApplyEventContext,
  outcome: ApplyEventSuccess,
): Promise<ApplyEventSuccess> {
  if (typeof ctx.sinceCursor === 'string' && outcome.event) {
    const page = await listByPrefix<Event>(
      store,
      EVENT_KEY_PREFIX,
      { limit: 1000, cursor: ctx.sinceCursor, sortOrder: 'asc' },
      (e) => e.eventId,
    );
    return {
      ...outcome,
      eventPage: { events: page.data, cursor: page.cursor, hasMore: page.hasMore },
    };
  }
  if (outcome.eventPage !== undefined) return outcome;
  if (ctx.eventCount === undefined || !outcome.event) return outcome;

  // The report half of bump-and-report: the events occupying the slots
  // between the one the writer asked for and the one its write landed on.
  // `cursor` stays null: the report is a lower bound, not a read position.
  const askedFor = ctx.eventCount;
  const committedSlot = eventIdToSlot(outcome.event.eventId);
  if (committedSlot === null || askedFor < FIRST_EVENT_SLOT || committedSlot <= askedFor + 1) {
    return outcome;
  }
  const span = committedSlot - askedFor - 1;
  const entries = await store.list<Event>({
    prefix: EVENT_KEY_PREFIX,
    startAfter: `${EVENT_KEY_PREFIX}${slotToEventId(askedFor)}`,
    end: `${EVENT_KEY_PREFIX}${outcome.event.eventId}`,
    limit: span,
  });
  const events = Array.from(entries.values());
  return {
    ...outcome,
    eventPage: { events, cursor: null, hasMore: events.length < span },
  };
}

async function applyEventCore(
  store: EventStore,
  ctx: ApplyEventContext,
): Promise<ApplyEventOutcome> {
  const { runId, data, now } = ctx;
  const specVersion = data.specVersion ?? SPEC_VERSION_CURRENT;

  // Slot base for this transaction. The DO serializes applyEvent calls and
  // the storage transaction makes the read atomic with every append below,
  // so `baseSlot + n` is the store-settled position of the nth append.
  const baseSlot = await lastCommittedSlot(store);
  if (baseSlot === null) {
    return failure(
      'LEGACY_RUN_NOT_SUPPORTED',
      `Run "${runId}" has ULID-numbered events and cannot be replayed by this world; drain it on the 4.x build`,
    );
  }
  let allocated = 0;

  /** Build and validate the stored event BEFORE anything is persisted. The
   * slot is drawn at the append; guard failures return before any append, so
   * the log stays dense. */
  const buildEvent = (record: Record<string, unknown>): Event => {
    allocated += 1;
    const withMeta: Record<string, unknown> = {
      ...record,
      runId,
      eventId: slotToEventId(baseSlot + allocated),
      createdAt: now,
      specVersion,
    };
    // eventData belongs on run_created only; run_started must not carry it.
    if (record.eventType === 'run_started') {
      delete withMeta.eventData;
    }
    return EventSchema.parse(compact(withMeta));
  };

  const putEvent = async (event: Event): Promise<void> => {
    await store.put(`${EVENT_KEY_PREFIX}${event.eventId}`, event);
  };

  // ============================================================
  // VALIDATION: current run state (skipped for run_created and for
  // step_completed / step_retrying, matching upstream; those only operate
  // on running steps regardless of run state).
  // ============================================================
  let currentRun: WorkflowRun | undefined;
  const skipRunValidation =
    data.eventType === 'run_created' ||
    data.eventType === 'step_completed' ||
    data.eventType === 'step_retrying';
  if (!skipRunValidation) {
    currentRun = await store.get<WorkflowRun>(RUN_KEY);
  }

  // ============================================================
  // RESILIENT START: run_started on a non-existent run bootstraps the run
  // from the message's runInput (spec >= 3 queue transport).
  // ============================================================
  let bootstrapped: ApplyEventSuccess['runCreated'];
  if (data.eventType === 'run_started' && !currentRun && data.eventData) {
    const {
      deploymentId,
      workflowName,
      input,
      executionContext,
      attributes,
      allowReservedAttributes,
      encryptionPublicKey,
    } = data.eventData;
    if (deploymentId && workflowName && input !== undefined) {
      const invalid = validateAttributes(seedAttributeChanges(attributes), {
        allowReservedAttributes: allowReservedAttributes === true,
      });
      if (invalid) return invalid;
      const createdRun = WorkflowRunSchema.parse(
        compact({
          runId,
          deploymentId,
          workflowName,
          specVersion,
          executionContext,
          input,
          status: 'pending',
          output: undefined,
          error: undefined,
          attributes: attributes ?? {},
          encryptionPublicKey,
          startedAt: undefined,
          completedAt: undefined,
          createdAt: now,
          updatedAt: now,
        }),
      );
      // Synthetic run_created event: it takes the earlier slot, so it
      // replays first.
      const runCreatedEvent = buildEvent({
        eventType: 'run_created',
        eventData: {
          deploymentId,
          workflowName,
          input,
          executionContext,
          attributes,
          allowReservedAttributes,
          encryptionPublicKey,
        },
      });
      await store.put(RUN_KEY, createdRun);
      await putEvent(runCreatedEvent);
      currentRun = createdRun;
      bootstrapped = { workflowName, createdAt: now };
    }
  }

  // ============================================================
  // VERSION COMPATIBILITY
  // ============================================================
  if (currentRun) {
    if (requiresNewerWorld(currentRun.specVersion)) {
      return failure(
        'RUN_NOT_SUPPORTED',
        `Run "${runId}" requires a newer world (run specVersion ${currentRun.specVersion}, world ${SPEC_VERSION_CURRENT})`,
        { runSpecVersion: currentRun.specVersion },
      );
    }
    if (isLegacySpecVersion(currentRun.specVersion)) {
      return failure(
        'LEGACY_RUN_NOT_SUPPORTED',
        `Run "${runId}" was created with a legacy spec version (${currentRun.specVersion ?? 'undefined'}) not supported by this world`,
      );
    }
  }

  // Lazy step start: a step_started carrying step-creation data (stepName +
  // input) may arrive with no prior step_created and creates the step on the
  // fly, mirroring the resilient run_started path.
  const createsChildEntity = isChildEntityCreationEvent(data);
  const lazyStepStart = createsChildEntity && data.eventType === 'step_started';

  // ============================================================
  // GUARDS: terminal run state
  // ============================================================
  if (currentRun && isTerminalWorkflowRunStatus(currentRun.status)) {
    // Idempotent: run_cancelled on an already-cancelled run records the event
    // and returns the current state.
    if (data.eventType === 'run_cancelled' && currentRun.status === 'cancelled') {
      const event = buildEvent({ ...data });
      await putEvent(event);
      return { ok: true, event, run: currentRun, releasedHooks: [] };
    }
    if (data.eventType === 'run_started') {
      return failure(
        'RUN_EXPIRED',
        `Workflow run "${runId}" is already in terminal state "${currentRun.status}"`,
      );
    }
    if (
      data.eventType === 'run_completed' ||
      data.eventType === 'run_failed' ||
      data.eventType === 'run_cancelled'
    ) {
      return failure(
        'ENTITY_CONFLICT',
        `Cannot transition run from terminal state "${currentRun.status}"`,
      );
    }
    if (createsChildEntity) {
      return failure(
        'ENTITY_CONFLICT',
        `Cannot create new entities on run in terminal state "${currentRun.status}"`,
      );
    }
    if (data.eventType === 'attr_set') {
      return failure(
        'ENTITY_CONFLICT',
        `Cannot set attributes on run in terminal state "${currentRun.status}"`,
      );
    }
  }

  // ============================================================
  // GUARDS: step ordering and terminal state
  // ============================================================
  let validatedStep: Step | undefined;
  if (
    data.eventType === 'step_started' ||
    data.eventType === 'step_completed' ||
    data.eventType === 'step_failed' ||
    data.eventType === 'step_retrying'
  ) {
    validatedStep = await store.get<Step>(`${STEP_KEY_PREFIX}${data.correlationId}`);
    if (!validatedStep && !lazyStepStart) {
      return failure('STEP_NOT_FOUND', `Step "${data.correlationId}" not found`);
    }
    // Lazy start exactly-once gate: a lazy step_started always CREATES the
    // step. An existing step means a concurrent handler won the create;
    // EntityConflictError maps to `skipped` in the runtime's executeStep.
    if (lazyStepStart && validatedStep) {
      return failure('ENTITY_CONFLICT', `Step "${data.correlationId}" already created`);
    }
    if (validatedStep) {
      if (isTerminalStepStatus(validatedStep.status)) {
        return failure(
          'ENTITY_CONFLICT',
          `Cannot modify step in terminal state "${validatedStep.status}"`,
        );
      }
      // On terminal runs, only in-flight steps may still record progress.
      if (
        currentRun &&
        isTerminalWorkflowRunStatus(currentRun.status) &&
        validatedStep.status !== 'running'
      ) {
        return failure(
          'RUN_EXPIRED',
          `Cannot modify non-running step on run in terminal state "${currentRun.status}"`,
        );
      }
    }
  }

  // ============================================================
  // GUARDS: hook event ordering
  // ============================================================
  if (
    (data.eventType === 'hook_disposed' || data.eventType === 'hook_received') &&
    data.correlationId
  ) {
    const existingHook = await store.get<Hook>(`${HOOK_KEY_PREFIX}${data.correlationId}`);
    if (!existingHook) {
      return failure('HOOK_NOT_FOUND', `Hook "${data.correlationId}" not found`);
    }
  }

  // Non-run_created events require the run to exist (after the resilient
  // start bootstrap had its chance). step_completed / step_retrying skip the
  // run read entirely; their step guard above already proves the run exists.
  if (!skipRunValidation && data.eventType !== 'run_started' && !currentRun) {
    return failure('RUN_NOT_FOUND', `Workflow run "${runId}" not found`);
  }

  // ============================================================
  // EVENT + ENTITY WRITES (single transaction)
  // ============================================================
  switch (data.eventType) {
    case 'run_created': {
      const existing = await store.get<WorkflowRun>(RUN_KEY);
      if (existing) {
        // Duplicate run_created: reject with the conflict outcome (mapped to
        // EntityConflictError at the storage layer) instead of returning the
        // existing run. Core treats the 409 as benign ("the run already
        // exists"), and every world now shares this contract.
        return failure('ENTITY_CONFLICT', `Workflow run "${runId}" already exists`);
      }
      const invalid = validateAttributes(seedAttributeChanges(data.eventData.attributes), {
        allowReservedAttributes: data.eventData.allowReservedAttributes === true,
      });
      if (invalid) return invalid;
      const run = WorkflowRunSchema.parse(
        compact({
          runId,
          deploymentId: data.eventData.deploymentId,
          workflowName: data.eventData.workflowName,
          specVersion,
          executionContext: data.eventData.executionContext,
          input: data.eventData.input,
          status: 'pending',
          output: undefined,
          error: undefined,
          attributes: data.eventData.attributes ?? {},
          encryptionPublicKey: data.eventData.encryptionPublicKey,
          startedAt: undefined,
          completedAt: undefined,
          createdAt: now,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(RUN_KEY, run);
      await putEvent(event);
      return {
        ok: true,
        event,
        run,
        releasedHooks: [],
        runCreated: { workflowName: data.eventData.workflowName, createdAt: now },
      };
    }

    case 'run_started': {
      if (!currentRun) {
        return failure('RUN_NOT_FOUND', `Workflow run "${runId}" not found`);
      }
      // Idempotent for concurrent invocations / queue redeliveries: if the
      // run is already running this is a replay: no duplicate event.
      if (currentRun.status === 'running') {
        return {
          ok: true,
          run: currentRun,
          releasedHooks: [],
          ...(ctx.skipPreload ? {} : { eventPage: await preloadAllEvents(store) }),
        };
      }
      const run = WorkflowRunSchema.parse(
        compact({
          ...currentRun,
          status: 'running',
          output: undefined,
          error: undefined,
          completedAt: undefined,
          startedAt: currentRun.startedAt ?? now,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(RUN_KEY, run);
      await putEvent(event);
      return {
        ok: true,
        event,
        run,
        releasedHooks: [],
        runCreated: bootstrapped,
        // Preload the log so the runtime can skip the initial events.list.
        ...(ctx.skipPreload ? {} : { eventPage: await preloadAllEvents(store) }),
      };
    }

    case 'run_completed': {
      if (!currentRun) {
        return failure('RUN_NOT_FOUND', `Workflow run "${runId}" not found`);
      }
      const run = WorkflowRunSchema.parse(
        compact({
          ...currentRun,
          status: 'completed',
          output: data.eventData.output,
          error: undefined,
          completedAt: now,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(RUN_KEY, run);
      await putEvent(event);
      const releasedHooks = await releaseAllHooks(store);
      await deleteAllWaits(store);
      return { ok: true, event, run, releasedHooks };
    }

    case 'run_failed': {
      if (!currentRun) {
        return failure('RUN_NOT_FOUND', `Workflow run "${runId}" not found`);
      }
      // The serialized error payload is stored verbatim.
      const run = WorkflowRunSchema.parse(
        compact({
          ...currentRun,
          status: 'failed',
          output: undefined,
          error: data.eventData.error,
          errorCode: data.eventData.errorCode,
          completedAt: now,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(RUN_KEY, run);
      await putEvent(event);
      const releasedHooks = await releaseAllHooks(store);
      await deleteAllWaits(store);
      return { ok: true, event, run, releasedHooks };
    }

    case 'run_cancelled': {
      if (!currentRun) {
        return failure('RUN_NOT_FOUND', `Workflow run "${runId}" not found`);
      }
      const run = WorkflowRunSchema.parse(
        compact({
          ...currentRun,
          status: 'cancelled',
          output: undefined,
          error: undefined,
          completedAt: now,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(RUN_KEY, run);
      await putEvent(event);
      const releasedHooks = await releaseAllHooks(store);
      await deleteAllWaits(store);
      return { ok: true, event, run, releasedHooks };
    }

    case 'attr_set': {
      if (!currentRun) {
        return failure('RUN_NOT_FOUND', `Workflow run "${runId}" not found`);
      }
      const invalid = validateAttributes(data.eventData.changes, {
        existingKeys: Object.keys(currentRun.attributes ?? {}),
        allowReservedAttributes: data.eventData.allowReservedAttributes === true,
      });
      if (invalid) return invalid;
      // Claim only after validation: a validation failure must leave the
      // correlationId unclaimed so a retry is not misreported as a dup.
      if (data.correlationId && data.eventData.writer.type === 'workflow') {
        const claimKey = `${ATTR_EVENT_MARKER_PREFIX}${data.correlationId}`;
        const claimed = await store.get<string>(claimKey);
        if (claimed !== undefined) {
          return failure(
            'ENTITY_CONFLICT',
            `Attribute event "${data.correlationId}" already exists`,
          );
        }
        await store.put(claimKey, '1');
      }
      const run = WorkflowRunSchema.parse(
        compact({
          ...currentRun,
          attributes: applyAttributeChanges(currentRun.attributes ?? {}, data.eventData.changes),
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(RUN_KEY, run);
      await putEvent(event);
      return { ok: true, event, run, releasedHooks: [] };
    }

    case 'step_created': {
      const stepKey = `${STEP_KEY_PREFIX}${data.correlationId}`;
      const existing = await store.get<Step>(stepKey);
      if (existing) {
        // Core catches EntityConflictError for exactly this replay case
        // ("Step already exists, continuing").
        return failure('ENTITY_CONFLICT', `Step "${data.correlationId}" already exists`);
      }
      const step = StepSchema.parse(
        compact({
          runId,
          stepId: data.correlationId,
          stepName: data.eventData.stepName,
          status: 'pending',
          input: data.eventData.input,
          output: undefined,
          error: undefined,
          attempt: 0,
          startedAt: undefined,
          completedAt: undefined,
          retryAfter: undefined,
          createdAt: now,
          updatedAt: now,
          specVersion,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(stepKey, step);
      await putEvent(event);
      return { ok: true, event, step, releasedHooks: [] };
    }

    case 'step_started': {
      const stepKey = `${STEP_KEY_PREFIX}${data.correlationId}`;
      let step = validatedStep;
      let stepCreatedLazily = false;
      if (!step && lazyStepStart && data.eventData) {
        // Lazy path: create the step plus a synthetic step_created event at
        // the prior slot, then transition it below.
        const { stepName, input } = data.eventData;
        if (typeof stepName !== 'string' || input === undefined) {
          return failure('STEP_NOT_FOUND', `Step "${data.correlationId}" not found`);
        }
        step = StepSchema.parse(
          compact({
            runId,
            stepId: data.correlationId,
            stepName,
            status: 'pending',
            input,
            attempt: 0,
            createdAt: now,
            updatedAt: now,
            specVersion,
          }),
        );
        const stepCreatedEvent = buildEvent({
          eventType: 'step_created',
          correlationId: data.correlationId,
          eventData: { stepName, input },
        });
        await store.put(stepKey, step);
        await putEvent(stepCreatedEvent);
        stepCreatedLazily = true;
      }
      if (!step) {
        return failure('STEP_NOT_FOUND', `Step "${data.correlationId}" not found`);
      }
      if (step.retryAfter && step.retryAfter.getTime() > now.getTime()) {
        return failure(
          'TOO_EARLY',
          `Cannot start step "${data.correlationId}": retryAfter timestamp has not been reached yet`,
          {
            retryAfterSeconds: Math.ceil((step.retryAfter.getTime() - now.getTime()) / 1000),
          },
        );
      }
      const updated = StepSchema.parse(
        compact({
          ...step,
          status: 'running',
          // Only set startedAt on the first start; increment attempt each start.
          startedAt: step.startedAt ?? now,
          attempt: step.attempt + 1,
          retryAfter: undefined,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(stepKey, updated);
      await putEvent(event);
      return {
        ok: true,
        event,
        step: updated,
        releasedHooks: [],
        ...(stepCreatedLazily ? { stepCreated: true as const } : {}),
      };
    }

    case 'step_completed': {
      const step = validatedStep;
      if (!step) {
        return failure('STEP_NOT_FOUND', `Step "${data.correlationId}" not found`);
      }
      const updated = StepSchema.parse(
        compact({
          ...step,
          status: 'completed',
          output: data.eventData.result,
          completedAt: now,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(`${STEP_KEY_PREFIX}${data.correlationId}`, updated);
      await putEvent(event);
      return { ok: true, event, step: updated, releasedHooks: [] };
    }

    case 'step_failed': {
      const step = validatedStep;
      if (!step) {
        return failure('STEP_NOT_FOUND', `Step "${data.correlationId}" not found`);
      }
      const updated = StepSchema.parse(
        compact({
          ...step,
          status: 'failed',
          error: data.eventData.error,
          completedAt: now,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(`${STEP_KEY_PREFIX}${data.correlationId}`, updated);
      await putEvent(event);
      return { ok: true, event, step: updated, releasedHooks: [] };
    }

    case 'step_retrying': {
      const step = validatedStep;
      if (!step) {
        return failure('STEP_NOT_FOUND', `Step "${data.correlationId}" not found`);
      }
      const updated = StepSchema.parse(
        compact({
          ...step,
          status: 'pending',
          error: data.eventData.error,
          retryAfter: data.eventData.retryAfter,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(`${STEP_KEY_PREFIX}${data.correlationId}`, updated);
      await putEvent(event);
      return { ok: true, event, step: updated, releasedHooks: [] };
    }

    case 'hook_created': {
      const hookId = data.correlationId;
      const token = data.eventData.token;
      const holder = ctx.tokenHolder ?? null;
      const markerKey = `${HOOK_EVENT_MARKER_PREFIX}${hookId}`;
      const hookKey = `${HOOK_KEY_PREFIX}${hookId}`;

      if (holder && (holder.runId !== runId || holder.hookId !== hookId)) {
        // A different (runId, hookId) holds this token. Record a
        // hook_conflict event carrying conflictingRunId so the claiming
        // workflow fails deterministically when the hook is awaited. The
        // legitimate holder's KV index entry is left untouched.
        const event = buildEvent({
          eventType: 'hook_conflict',
          correlationId: hookId,
          eventData: { token, conflictingRunId: holder.runId },
        });
        await putEvent(event);
        return { ok: true, event, releasedHooks: [] };
      }

      const existingMarker = await store.get<string>(markerKey);
      if (existingMarker !== undefined) {
        const existingHook = await store.get<Hook>(hookKey);
        if (existingHook && !holder) {
          // Crash orphan: hook + event committed but the global KV index
          // write was lost. Complete the partial write by re-indexing.
          return { ok: true, hook: existingHook, hookToIndex: existingHook, releasedHooks: [] };
        }
        // Fully-committed duplicate (or re-create after disposal): reject so
        // the runtime's concurrent-replay catch path can swallow it.
        return failure('ENTITY_CONFLICT', `Hook "${hookId}" already created`);
      }

      const hook = HookSchema.parse(
        compact({
          runId,
          hookId,
          token,
          metadata: data.eventData.metadata,
          ownerId: '',
          projectId: '',
          environment: '',
          createdAt: now,
          specVersion,
          isWebhook: data.eventData.isWebhook,
          isSystem: data.eventData.isSystem,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(hookKey, hook);
      await store.put(markerKey, event.eventId);
      await putEvent(event);
      return { ok: true, event, hook, hookToIndex: hook, releasedHooks: [] };
    }

    case 'hook_disposed': {
      const hookKey = `${HOOK_KEY_PREFIX}${data.correlationId}`;
      // Existence was validated above; read again for the token.
      const hook = await store.get<Hook>(hookKey);
      if (!hook) {
        return failure('HOOK_NOT_FOUND', `Hook "${data.correlationId}" not found`);
      }
      await store.delete(hookKey);
      const event = buildEvent({ ...data });
      await putEvent(event);
      return {
        ok: true,
        event,
        releasedHooks: [{ hookId: hook.hookId, token: hook.token }],
      };
    }

    case 'wait_created': {
      const waitKey = `${WAIT_KEY_PREFIX}${data.correlationId}`;
      const existing = await store.get<Wait>(waitKey);
      if (existing) {
        // Core catches EntityConflictError for exactly this replay case
        // ("Wait already exists, continuing").
        return failure('ENTITY_CONFLICT', `Wait "${data.correlationId}" already exists`);
      }
      const wait = WaitSchema.parse(
        compact({
          waitId: `${runId}-${data.correlationId}`,
          runId,
          status: 'waiting',
          resumeAt: data.eventData.resumeAt,
          completedAt: undefined,
          createdAt: now,
          updatedAt: now,
          specVersion,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(waitKey, wait);
      await putEvent(event);
      return { ok: true, event, wait, releasedHooks: [] };
    }

    case 'wait_completed': {
      const waitKey = `${WAIT_KEY_PREFIX}${data.correlationId}`;
      const existing = await store.get<Wait>(waitKey);
      if (!existing) {
        return failure('WAIT_NOT_FOUND', `Wait "${data.correlationId}" not found`);
      }
      if (existing.status === 'completed') {
        return failure('ENTITY_CONFLICT', `Wait "${data.correlationId}" already completed`);
      }
      const wait = WaitSchema.parse(
        compact({
          ...existing,
          status: 'completed',
          completedAt: now,
          updatedAt: now,
        }),
      );
      const event = buildEvent({ ...data });
      await store.put(waitKey, wait);
      await putEvent(event);
      return { ok: true, event, wait, releasedHooks: [] };
    }

    // hook_received and hook_conflict are event-only at the storage level for
    // this world. `noop` never reaches here: slots are allocated at the
    // commit, so this world has no holes to seal.
    default: {
      const event = buildEvent({ ...data });
      await putEvent(event);
      return { ok: true, event, releasedHooks: [] };
    }
  }
}
